version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      web-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      docker-dependencies:
        patterns:
          - "*"
