packages:
  - "apps/*"
  - "packages/*"
catalog:
  react: "19.3.0"
  react-dom: "19.3.0"
  "@types/react": "19.3.0"
  "@types/react-dom": "19.3.0"
  "@biomejs/biome": "2.5.14"
  typescript: "7.0.2"
  oxlint: "1.83.0"
  npm-run-all2: "9.0.3"
allowBuilds:
  '@scarf/scarf': false
  core-js: true
  esbuild: true
  lefthook: true
  protobufjs: true
auditLevel: moderate
