services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      DB_HOST: postgres
    security_opt:
      - apparmor=unconfined
    depends_on:
      postgres:
        condition: service_healthy
