# This workflow is managed by gh actions-lock.

name: Lint Markdown files
on:
  pull_request:
    paths:
      - "**/*.md"
      - .markdownlint-cli2.jsonc
      - .markdownlintignore

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@v4.3.0
        with:
          install: true
      - name: Run markdownlint
        run: mise exec -- markdownlint-cli2 "**/*.md"
